mypoll/urls.py
from django.urls import path

from . import views

app_name = "mypoll"

urlpatterns = [
    path("",views.index,name = "index"),
    path("mypoll/<int:question_id>/",views.detail,name = "detail"),
    path("mypoll/<int:question_id>/vote/",views.vote,name = "vote"),
    path("mypoll/<int:question_id>/results/",views.results,name = "results"),
]

mypoll/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date - publish")

    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete =models.CASCADE )
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mypoll/views.py
from django.shortcuts import render ,HttpResponse  , get_object_or_404
from django.db.models import F
from django.urls import reverse
# from django.template import loader
from .models import Question ,Choice
from django.http import Http404 ,HttpResponseRedirect
# Create your views here.
def index(request):
    question_ls = Question.objects.all()
    # template =  loader.get_template("mypoll/index.html")
    context = {"question_ls" : question_ls }
    return render(request,"mypoll/index.html",context)

def detail(request,question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("question dpes not exit")
    choice  = Choice.objects.filter(question = question)
    context = {"choice" : choice,
               "question" : question}

    return render(request,"mypoll/detail.html",context)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "mypoll/results.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question,pk = question_id)
    try:
        selected_choice = question.choice_set.get(pk = request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request,"mypoll/detail.html",
                      {
                          "question" : question,
                          "error_message" : "you did not select a choice",
                          "selected_Choice" : selected_choice
                      },
                    )   
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("mypoll:results", args=(question.id,)))

mypoll/templates/mypoll/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
</head>
<body>
    <h1>you are looking at question {{question.id}}</h1>
    <form action="{% url 'mypoll:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
</body>
</html>

mypoll/templates/mypoll/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>mypoll</title>
</head>
<body>   
    <h1>mypoll</h1>
    <div>
        {% if question_ls %}
        <ul>
            {% for question in question_ls %}
            <li><a href="/mypoll/{{ question.id }}/">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    </div>
</body>
</html>

mypoll/templates/mypoll/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'mypoll:detail' question.id %}">Vote again?</a>